# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 21:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('work_study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Cannot contain spaces', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(regex=re.compile('^[A-z\\-_1234567890]+$', 32))])),
                ('long_name', models.CharField(blank=True, max_length=255)),
                ('directions', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Companies: pickup',
            },
        ),
    ]
