# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_study', '0002_pickuplocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('fname', models.CharField(blank=True, max_length=150, null=True)),
                ('lname', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('phone_cell', models.CharField(blank=True, max_length=25, null=True)),
                ('fax', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=75, null=True)),
            ],
            options={
                'verbose_name': 'Contact supervisor',
                'ordering': ('lname',),
            },
        ),
    ]
