# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 21:43
from __future__ import unicode_literals

import custom_field.custom_field
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('work_study', '0004_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inactive', models.BooleanField(default=False, help_text="Will unset student's placements.")),
                ('team_name', models.CharField(max_length=255, unique=True)),
                ('paying', models.CharField(blank=True, choices=[('P', 'Paying'), ('N', 'Non-Paying'), ('F', 'Funded')], max_length=1)),
                ('funded_by', models.CharField(blank=True, max_length=150)),
                ('industry_type', models.CharField(blank=True, max_length=100)),
                ('travel_route', models.CharField(blank=True, db_column='train_line', help_text='Train or van route', max_length=50)),
                ('stop_location', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip', models.CharField(blank=True, max_length=10)),
                ('directions_to', models.TextField(blank=True)),
                ('directions_pickup', models.TextField(blank=True)),
                ('map', models.ImageField(blank=True, upload_to='maps')),
                ('use_google_maps', models.BooleanField(default=False)),
                ('company_description', models.TextField(blank=True)),
                ('job_description', models.TextField(blank=True)),
                ('time_earliest', models.TimeField(blank=True, null=True)),
                ('time_latest', models.TimeField(blank=True, null=True)),
                ('time_ideal', models.TimeField(blank=True, null=True)),
                ('am_transport_group', models.ForeignKey(blank=True, db_column='dropoff_location_id', help_text='Group for morning drop-off, can be used for work study attendance.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workteamset_dropoff', to='work_study.PickupLocation')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_study.Company')),
                ('contacts', models.ManyToManyField(blank=True, help_text='All contacts at this company. You must select them here in order to select the primary contact for a student.', to='work_study.Contact')),
                ('cras', models.ManyToManyField(blank=True, null=True, to='work_study.CraContact')),
            ],
            options={
                'ordering': ('team_name',),
            },
            bases=(models.Model, custom_field.custom_field.CustomFieldModel),
        ),
        migrations.CreateModel(
            name='WorkTeamUser',
            fields=[
            ],
            options={
                'proxy': True,
                'ordering': ('last_name', 'first_name'),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='workteam',
            name='login',
            field=models.ManyToManyField(blank=True, help_text='Optional. This creates users with "company" permissions, allowing them to sign into the database to review/approve pending and past time sheets for the assigned workteam.', to='work_study.WorkTeamUser'),
        ),
        migrations.AddField(
            model_name='workteam',
            name='pm_transport_group',
            field=models.ForeignKey(blank=True, db_column='pickup_location_id', help_text='Group for evening pick-up, can be used for work study attendance. If same as dropoff, you may omit this field.', null=True, on_delete=django.db.models.deletion.CASCADE, to='work_study.PickupLocation'),
        ),
    ]
