# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_study', '0005_auto_20170505_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workteam',
            name='cras',
            field=models.ManyToManyField(blank=True, to='work_study.CraContact'),
        ),
    ]
