# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 22:26
from __future__ import unicode_literals

import admissions.models
import custom_field.custom_field
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import sis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sis', '0007_percoursesectioncohort'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=True, help_text='When true, applicant cannot meet any level beyond this. When false, applicant can leapfrog check items.')),
            ],
            options={
                'ordering': ('level', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AdmissionLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9- ]*$', message='Must be Alphanumeric')])),
                ('order', models.IntegerField(help_text='Order in which level appears, 1 being first.', unique=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255, verbose_name='First Name')),
                ('mname', models.CharField(blank=True, max_length=255, verbose_name='Middle Name')),
                ('lname', models.CharField(max_length=255, verbose_name='Last Name')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='applicant_pics')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('bday', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('unique_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('street', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, max_length=360)),
                ('state', models.CharField(blank=True, max_length=360)),
                ('zip', models.CharField(blank=True, max_length=10)),
                ('ssn', models.CharField(blank=True, max_length=11, verbose_name='SSN')),
                ('parent_email', models.EmailField(blank=True, max_length=254)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('hs_grad_yr', models.IntegerField(blank=True, null=True)),
                ('elem_grad_yr', models.IntegerField(blank=True, null=True)),
                ('present_school_typed', models.CharField(blank=True, help_text='This is intended for applicants to apply for the school. Administrators should use the above.', max_length=255)),
                ('present_school_type_typed', models.CharField(blank=True, max_length=255)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('parent_guardian_first_name', models.CharField(blank=True, max_length=150)),
                ('parent_guardian_last_name', models.CharField(blank=True, max_length=150)),
                ('relationship_to_student', models.CharField(blank=True, max_length=500)),
                ('from_online_inquiry', models.BooleanField(default=False)),
                ('ready_for_export', models.BooleanField(default=False)),
                ('total_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adjusted_available_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calculated_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_added', models.DateField(auto_now_add=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1))])),
                ('withdrawn_note', models.CharField(blank=True, max_length=500)),
                ('first_to_college', models.BooleanField(default=False)),
                ('individual_education_plan', models.BooleanField(default=False)),
                ('lives_with', models.CharField(blank=True, choices=[('Both Parents', 'Both Parents'), ('Mother', 'Mother'), ('Father', 'Father'), ('Guardian(s)', 'Guardian(s)')], max_length=50)),
            ],
            options={
                'ordering': ('lname', 'fname'),
            },
            bases=(models.Model, custom_field.custom_field.CustomFieldModel),
        ),
        migrations.CreateModel(
            name='ApplicantAdditionalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionals', to='admissions.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantCustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_field_integrated_with_applicant', models.BooleanField(default=False)),
                ('field_type', models.CharField(blank=True, choices=[('input', 'Small Text Field'), ('textarea', 'Large Text Field'), ('multiple', 'Dropdown Choices'), ('radio', 'Multiple Choices'), ('checkbox', 'Checkboxes'), ('emergency_contact', 'Emergency Contact')], help_text='Choose the type of field', max_length=50, null=True)),
                ('field_label', models.CharField(blank=True, help_text='Give this field a recognizable name', max_length=255, null=True)),
                ('field_choices', models.TextField(blank=True, help_text='List the choices you want displayed,\nseperated by commas. This is only valid for Dropdown,\nMultiple, and Checkbox field types', null=True)),
                ('helptext', models.CharField(blank=True, max_length=500, null=True)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_file', models.FileField(upload_to='applicant_files')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDecisionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('level', models.ManyToManyField(blank=True, help_text='This decision can apply for these levels.', to='admissions.AdmissionLevel')),
            ],
        ),
        migrations.CreateModel(
            name='BoroughOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1))])),
                ('note', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.Applicant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CountryOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EthnicityChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeederSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FirstContactOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HeardAboutUsOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImmigrationOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OpenHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1))])),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='PlaceOfWorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReligionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentApplicationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('json_template', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawnChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Withdrawn choices',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='feederschool',
            name='school_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.SchoolType'),
        ),
        migrations.AddField(
            model_name='applicantadditionalinformation',
            name='custom_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.ApplicantCustomField'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='application_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.ApplicationDecisionOption'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='application_decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.Faculty'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='borough',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.BoroughOption'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='checklist',
            field=models.ManyToManyField(blank=True, to='admissions.AdmissionCheck'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='country_of_birth',
            field=models.ForeignKey(blank=True, default=admissions.models.get_default_country, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.CountryOption'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='ethnicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.EthnicityChoice'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='family_preferred_language',
            field=models.ForeignKey(blank=True, default=sis.models.get_default_language, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.LanguageChoice'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='first_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.FirstContactOption'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='heard_about_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.HeardAboutUsOption'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='immigration_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.ImmigrationOption'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.AdmissionLevel'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='open_house_attended',
            field=models.ManyToManyField(blank=True, to='admissions.OpenHouse'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='parent_guardians',
            field=models.ManyToManyField(blank=True, to='sis.EmergencyContact', verbose_name='Student contact'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='place_of_worship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.PlaceOfWorship'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='present_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.FeederSchool'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.ReligionChoice'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='school_year',
            field=models.ForeignKey(blank=True, default=admissions.models.get_school_year, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.SchoolYear'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='siblings',
            field=models.ManyToManyField(blank=True, related_name='_applicant_siblings_+', to='sis.Student'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='sis_student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appl_student', to='sis.Student'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='withdrawn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.WithdrawnChoices'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='year',
            field=models.ForeignKey(blank=True, default=admissions.models.get_year, help_text='Applying for this grade level', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.GradeLevel'),
        ),
        migrations.AddField(
            model_name='admissioncheck',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.AdmissionLevel'),
        ),
    ]
