# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0007_percoursesectioncohort'),
        ('schedule', '0006_award_awardstudent_omitcoursegpa_omityeargpa'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarkingPeriodGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cached_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='MP Average')),
                ('grade_recalculation_needed', models.BooleanField(default=True)),
                ('marking_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.MarkingPeriod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='studentmarkingperiodgrade',
            unique_together=set([('student', 'marking_period')]),
        ),
    ]
