# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 22:44
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sis', '0007_percoursesectioncohort'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('major_offense', models.BooleanField(default=False, help_text='This can be filtered by Grade Analytics and other reports.')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineActionInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discipline.DisciplineAction')),
            ],
        ),
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(help_text='If comment is "Case note" these infractions will not be counted as a discipline issue in reports', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today, validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1))])),
                ('comments', models.TextField(blank=True)),
                ('private_note', models.TextField(blank=True)),
                ('action', models.ManyToManyField(through='discipline.DisciplineActionInstance', to='discipline.DisciplineAction')),
                ('infraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discipline.Infraction')),
                ('students', models.ManyToManyField(to='sis.Student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis.Faculty')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='disciplineactioninstance',
            name='student_discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discipline.StudentDiscipline'),
        ),
    ]
