# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefered_file_format', models.CharField(choices=[('o', 'Open Document Format (.odt, .ods)'), ('m', 'Microsoft Binary (.doc, .xls)'), ('x', 'Microsoft Office Open XML (.docx, .xlsx)')], default=sis.models.get_prefered_format, help_text='Open Document Format is recommended.', max_length=1, verbose_name='Preferred file format')),
                ('include_deleted_students', models.BooleanField(default=False, help_text='When searching for students, include deleted (previous) students.')),
                ('gradebook_preference', models.CharField(blank=True, choices=[('O', 'Online Gradebook'), ('S', 'Spreadsheet'), ('E', 'Engrade'), ('M', 'Manual')], max_length=10)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
