# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import sis.models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255, verbose_name='First Name')),
                ('mname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name')),
                ('lname', models.CharField(max_length=255, verbose_name='Last Name')),
                ('relationship_to_student', models.CharField(blank=True, max_length=500)),
                ('street', models.CharField(blank=True, help_text='Include apt number', max_length=255, null=True)),
                ('city', models.CharField(blank=True, default=sis.models.get_city, max_length=255, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pin', models.CharField(blank=True, max_length=6, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('primary_contact', models.BooleanField(default=True, help_text='This contact is where mailings should be sent to. In the event of an emergency, this is the person that will be contacted first.')),
                ('emergency_only', models.BooleanField(default=False, help_text='Only contact in case of emergency')),
                ('sync_schoolreach', models.BooleanField(default=True, help_text='Sync this contact with schoolreach')),
            ],
            options={
                'verbose_name': 'Student Contact',
                'ordering': ('primary_contact', 'lname'),
            },
        ),
        migrations.CreateModel(
            name='EmergencyContactNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('ext', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, choices=[('H', 'Home'), ('C', 'Cell'), ('W', 'Work'), ('O', 'Other')], max_length=2)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('primary', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.EmergencyContact')),
            ],
            options={
                'verbose_name': 'Student Contact Number',
            },
        ),
    ]
