# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0003_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Grade Number')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Grade Name')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
