# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import sis.models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0004_gradelevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', sis.models.IntegerRangeField(help_text='Example 2014', unique=True)),
                ('full_name', models.CharField(blank=True, help_text='Example Class of 2014', max_length=255)),
            ],
            options={
                'verbose_name': 'Graduating Class',
                'verbose_name_plural': 'Graduating Classes',
            },
        ),
        migrations.CreateModel(
            name='LanguageChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('iso_code', models.CharField(blank=True, help_text='ISO 639-1 Language code http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes', max_length=2)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
    ]
