# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_award_awardstudent_omitcoursegpa_omityeargpa'),
        ('sis', '0006_auto_20170505_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerCourseSectionCohort',
            fields=[
                ('cohort_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sis.Cohort')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.CourseSection')),
            ],
            bases=('sis.cohort',),
        ),
    ]
