# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 09:28
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0007_percoursesectioncohort'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseSection',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('sis.student',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
