# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0009_auto_20170506_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='benchmark_grade',
            field=models.BooleanField(default='', help_text='Causes additional information to appear on transcripts. The configuration option "Benchmark-based grading" sets the default for this field.'),
        ),
    ]
