# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 17:44
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sis', '0006_auto_20170505_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('shortname', models.CharField(max_length=255)),
                ('start_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1))])),
                ('end_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1))])),
                ('grades_due', models.DateField(blank=True, help_text='If filled out, teachers will be notified when grades are due.', null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1))])),
                ('active', models.BooleanField(default=False, help_text='Teachers may only enter grades for active marking periods. There may be more than one active marking period.')),
                ('show_reports', models.BooleanField(default=True, help_text='If checked this marking period will show up on reports.')),
                ('school_days', models.IntegerField(blank=True, help_text='If set, this will be the number of days school is in session. If unset, the value is calculated by the days off.', null=True)),
                ('weight', models.DecimalField(decimal_places=3, default=1, help_text='Weight for this marking period when calculating grades.', max_digits=5)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.SchoolYear')),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
    ]
