# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20170505_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='enrollments',
            field=models.ManyToManyField(blank=True, through='schedule.CourseEnrollment', to='sis.Student'),
        ),
    ]
