# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20170505_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='cohorts',
            field=models.ManyToManyField(blank=True, to='sis.Cohort'),
        ),
    ]
