# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gradebook.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0006_award_awardstudent_omitcoursegpa_omityeargpa'),
        ('sis', '0007_percoursesectioncohort'),
        ('benchmarks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('points_possible', gradebook.models.GradeField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('allow_multiple_demonstrations', models.BooleanField(default=False)),
                ('demonstration_aggregation_method', models.CharField(blank=True, choices=[('Avg', 'Average'), ('Count', 'Count'), ('Max', 'Maximum'), ('Min', 'Minimum'), ('StdDev', 'Standard deviation'), ('Sum', 'Sum'), ('Variance', 'Variance')], max_length=16, null=True)),
                ('display_in_gradebook', models.BooleanField(default=True)),
                ('fixed_points_possible', gradebook.models.GradeField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fixed_granularity', gradebook.models.GradeField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('display_order', models.IntegerField(blank=True, null=True, unique=True)),
                ('display_scale', gradebook.models.GradeField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('display_symbol', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', gradebook.models.WeightField(decimal_places=4, default=1, max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sis.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='CalculationRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_possible', gradebook.models.GradeField(blank=True, decimal_places=2, default=100, help_text='A teachergradebook is out of this many points. Or the max possible points a student can earn. Common examples are 100 or 4.0.', max_digits=8, null=True)),
                ('decimal_places', models.IntegerField(default=2)),
                ('first_year_effective', models.ForeignKey(help_text='Rule also applies to subsequent years.', on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_calculationrule_set', to='sis.SchoolYear', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalculationRulePerCourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', gradebook.models.WeightField(decimal_places=4, default=1, max_digits=5)),
                ('apply_to_departments', models.ManyToManyField(blank=True, related_name='gradebook_calculationrulepercoursecategory_set', to='schedule.Department')),
                ('calculation_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per_course_category_set', to='gradebook.CalculationRule')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.AssignmentCategory')),
            ],
        ),
        migrations.CreateModel(
            name='CalculationRuleSubstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('>', 'Greater than'), ('>=', 'Greater than or equal to'), ('<=', 'Less than or equal to'), ('<', 'Less than'), ('!=', 'Not equal to'), ('==', 'Equal to')], max_length=2)),
                ('match_value', gradebook.models.GradeField(blank=True, decimal_places=2, help_text='Use only (0..1) unless category has fixed points possible.', max_digits=8, null=True)),
                ('display_as', models.CharField(blank=True, max_length=16, null=True)),
                ('calculate_as', gradebook.models.GradeField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('flag_visually', models.BooleanField(default=False)),
                ('apply_to_categories', models.ManyToManyField(blank=True, to='gradebook.AssignmentCategory')),
                ('apply_to_departments', models.ManyToManyField(blank=True, related_name='_calculationrulesubstitution_apply_to_departments_+', to='schedule.Department')),
                ('calculation_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_set', to='gradebook.CalculationRule')),
            ],
        ),
        migrations.CreateModel(
            name='Demonstration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', gradebook.models.GradeField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('normalized_mark', models.FloatField(blank=True, null=True)),
                ('letter_grade', models.CharField(blank=True, help_text='Overrides numerical mark.', max_length=3, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook.Assignment')),
                ('demonstration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gradebook.Demonstration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_mark_set', to='sis.Student')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gradebook.AssignmentType'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='benchmark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='benchmarks.Benchmark', verbose_name='standard'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gradebook.AssignmentCategory'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.CourseSection'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='marking_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.MarkingPeriod'),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together=set([('assignment', 'demonstration', 'student')]),
        ),
    ]
